services:
  words:
    image: words:latest
    ports:
      - "8081:8081"
    environment:
      - PG_NAME=words
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    depends_on:
      - postgres

  aggregator:
    image: aggregator:latest
    ports:
      - "8080:8080"
    depends_on:
      - words

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=words
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data:
    driver: local

