[package]
name = "words"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
rand = "0.9.1"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-postgres = "0.7.13"
